//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Default_Page
    {
        public int ID { get; set; }
        public string Default_Title { get; set; }
        public string Default_Slider_Image { get; set; }
        public string Default_Widgets { get; set; }
        public string Default_Articles_Links { get; set; }
        public string Default_Menu_Links { get; set; }
        public string UserID { get; set; }
    }
}
