//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultMenu
    {
        public int Id { get; set; }
        public string MenuNameId { get; set; }
        public string MenuName { get; set; }
        public string MenuDropDownId { get; set; }
        public string MenuDropDown { get; set; }
        public string UserId { get; set; }
        public string MenuUrl { get; set; }
    }
}
