//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderIcon
    {
        public int Id { get; set; }
        public string IconName { get; set; }
        public string IconUrl16x16 { get; set; }
        public string IconUrl32x32 { get; set; }
        public string IconUrl64x64 { get; set; }
        public string IconUrl128x128 { get; set; }
        public string IconUrl256x256 { get; set; }
    }
}
