//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatestComment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string UrlText { get; set; }
        public string Time { get; set; }
        public string Heading { get; set; }
        public string Message { get; set; }
        public string UserId { get; set; }
    }
}
