//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadImage
    {
        public int Id { get; set; }
        public string ImageId { get; set; }
        public string ImageUrl { get; set; }
        public string ToolTip { get; set; }
        public string Alt { get; set; }
        public string Select_Image_Type { get; set; }
        public string UserId { get; set; }
        public string page { get; set; }
    }
}
