//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandrill
    {
        public int id { get; set; }
        public string ts { get; set; }
        public string @event { get; set; }
        public string mssgtext { get; set; }
        public string mssghtml { get; set; }
        public string mssgfromemail { get; set; }
        public string mssgfromname { get; set; }
        public string mssgemail { get; set; }
        public string mssgsubject { get; set; }
        public string mssgsender { get; set; }
        public string mssgattachments { get; set; }
    }
}
