//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class odesk
    {
        public int id { get; set; }
        public string Date_from { get; set; }
        public string Date_to { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string emailid { get; set; }
        public string contactno { get; set; }
        public string amount { get; set; }
        public string noofdays { get; set; }
        public string code { get; set; }
    }
}
