//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageInfo
    {
        public int Id { get; set; }
        public string TextId { get; set; }
        public string TextContent { get; set; }
        public string PageNo { get; set; }
        public string UserId { get; set; }
    }
}
