//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pcongoEntities : DbContext
    {
        public pcongoEntities()
            : base("name=pcongoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public DbSet<Default_Page> Default_Page { get; set; }
        public DbSet<DefaultMenu> DefaultMenus { get; set; }
        public DbSet<FolderIcon> FolderIcons { get; set; }
        public DbSet<LatestComment> LatestComments { get; set; }
        public DbSet<LatestNew> LatestNews { get; set; }
        public DbSet<LoadImage> LoadImages { get; set; }
        public DbSet<LoadText> LoadTexts { get; set; }
        public DbSet<Mandrill> Mandrills { get; set; }
        public DbSet<odesk> odesks { get; set; }
        public DbSet<PageInfo> PageInfoes { get; set; }
        public DbSet<SliderImage> SliderImages { get; set; }
        public DbSet<SlidingArticle> SlidingArticles { get; set; }
        public DbSet<SocialNetworkingUrl> SocialNetworkingUrls { get; set; }
        public DbSet<UserBackgroundImage> UserBackgroundImages { get; set; }
        public DbSet<UserFolder> UserFolders { get; set; }
        public DbSet<UserMemorySpace> UserMemorySpaces { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<UtopiansTimeLine> UtopiansTimeLines { get; set; }
    }
}
