//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlidingArticle
    {
        public int Id { get; set; }
        public string HeadingId { get; set; }
        public string Heading { get; set; }
        public string UrlId1 { get; set; }
        public string Url2 { get; set; }
        public string UrlId2 { get; set; }
        public string Url3 { get; set; }
        public string UrlId3 { get; set; }
        public string Url1 { get; set; }
        public string ImageId1 { get; set; }
        public string ImageUrl1 { get; set; }
        public string ImageTooltip1 { get; set; }
        public string ImageAlt1 { get; set; }
        public string ContentId1 { get; set; }
        public string Content1 { get; set; }
        public string ImageId2 { get; set; }
        public string ImageUrl2 { get; set; }
        public string ImageTooltip2 { get; set; }
        public string ImageAlt2 { get; set; }
        public string ContentId2 { get; set; }
        public string Content2 { get; set; }
        public string ImageId3 { get; set; }
        public string ImageUrl3 { get; set; }
        public string ImageTooltip3 { get; set; }
        public string ImageAlt3 { get; set; }
        public string ContentId3 { get; set; }
        public string Content3 { get; set; }
        public string UserId { get; set; }
    }
}
