//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SliderImage
    {
        public int Id { get; set; }
        public string ImageUrlId { get; set; }
        public string ImageUrl { get; set; }
        public string ThumbUrlId { get; set; }
        public string ThumbUrl { get; set; }
        public string HeadingId { get; set; }
        public string Heading { get; set; }
        public string ContentId { get; set; }
        public string ContentText { get; set; }
        public string UrlId { get; set; }
        public string Url { get; set; }
        public string UrlTextId { get; set; }
        public string UrlText { get; set; }
        public string UserId { get; set; }
    }
}
