//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFolder
    {
        public int FId { get; set; }
        public string FolderIconName { get; set; }
        public string FolderImageUrl { get; set; }
        public string FolderTopImageIconUrl { get; set; }
        public string FolderTopTitle { get; set; }
        public string FolderLeftDiv { get; set; }
        public string FolderRightDiv { get; set; }
        public string FolderBottomText { get; set; }
        public string Username { get; set; }
    }
}
