//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMemorySpace
    {
        public int id { get; set; }
        public string c_drive { get; set; }
        public string d_drive { get; set; }
        public string e_drive { get; set; }
        public string username { get; set; }
    }
}
