//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcongo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtopiansTimeLine
    {
        public int Id { get; set; }
        public string evId { get; set; }
        public string evName { get; set; }
        public string evDate { get; set; }
    }
}
